### ISSUE TITLE
Which Ubuntu version should I use to run the program on AWS?

### ISSUE THREAD

**Issue by adam3q** [mhxie/reflex4arm#1]
At first, thanks for your wonderful work. Despite a lot of effort, I still can’t reproduce your work on AWS EC2.

I successfully ran the original reflex program on the Ubuntu16 system of AWS i3 series instances. But when I run reflex4arm on the aws-ec2 branch, I have encountered some problems on both the Ubuntu16 and Ubuntu18. My deployment is basically based on the README.md on the aws-ec2 branch. 

So I would like to ask whether the current README.md is out of date? What kind of system environment is needed to run the program successfully? Thank you!

### ubuntu 16 error message
**ubuntu@ip-172-31-8-120:~/elune/reflex4arm$ sudo ./ix**
11:25:18 <4>: init: starting IX
11:25:18 <4>: init: cpu phase
11:25:18 <4>: cpu: detected 8 cores
11:25:18 <4>: init: module CPU        SUCCESS
11:25:18 <4>: using config :'./ix.conf'
11:25:18 <4>: init: module cfgcpu     SUCCESS
11:25:18 <4>: init: module cfgmem     SUCCESS
Starting SPDK v19.04 / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: reflex --no-shconf -c 3 -n 1 --log-level=lib.eal:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid7783 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
PMD: LLQ is not supported. Fallback to host mode policy.
PMD: Placement policy: Regular
11:25:18 <4>: init: module dpdk       SUCCESS
11:25:19 <4>: timer: detected 2300 ticks per US (dpdk: 2300)
11:25:19 <4>: init: module timer      SUCCESS
mempool_datastore: pending_pkt     elem_len:56 nr_elems:1024
mempool_datastore: arp             elem_len:80 nr_elems:65536
11:25:19 <4>: init: module net        SUCCESS
11:25:19 <4>: no static arp entries defined in config
11:25:19 <4>: ------------1CFG.num_ethdev 1
11:25:19 <4>: ------------2CFG.num_ethdev 1
11:25:19 <4>: NVMe device model: sample-aws-ec2.devmodel
11:25:19 <4>: I/O Scheduler: ON
11:25:19 <4>: net: using the following configuration:
11:25:19 <4>:   host IP:        172.31.1.119
11:25:19 <4>:   broadcast IP:   172.31.15.255
11:25:19 <4>:   gateway IP:     172.31.0.1
11:25:19 <4>:   subnet mask:    255.255.240.0
11:25:19 <4>: init: module cfg        SUCCESS
11:25:19 <4>: init: module cp         SUCCESS
CPU 00| 11:25:19 <4>: cpu: started core 0, numa node 0
CPU 00| 11:25:19 <4>: init: module firstcpu   SUCCESS
mempool_mbuf_datastore: mbuf            elem_len:9128 nr_elems:20480
CPU 00| 11:25:19 <4>: init: module mbuf       SUCCESS
mempool_datastore: pbuf            elem_len:48 nr_elems:786432
mempool_datastore: pbuf_payload    elem_len:4096 nr_elems:262144
mempool_datastore: tcp_pcb         elem_len:272 nr_elems:262144
mempool_datastore: tcp_seg         elem_len:32 nr_elems:262144
CPU 00| 11:25:20 <4>: init: module memp       SUCCESS
mempool_datastore: pcb             elem_len:64 nr_elems:524288
mempool_datastore: ip              elem_len:16 nr_elems:524288
CPU 00| 11:25:20 <4>: init: module tcpapi     SUCCESS
We have 1 nb_ports now.
TX TCP checksum offloading is enabled
WARNING: RX Timestamp offloading not supported
nb_tx_queues is 0
nb_rx_queues is 0
PMD: Set MTU: 9000
Enable jumbo frames. MTU size is 9000
max_tx_queues is 8
max_rx_queues is 8
CPU 00| 11:25:20 <4>: Setting up TX queues for core 0... at socket 0
CPU 00| 11:25:20 <4>: Setting up TX queues for core 1... at socket 0
CPU 00| 11:25:20 <4>: Setting up RX queues for core 0... at socket 0
CPU 00| 11:25:20 <4>: Setting up RX queues for core 1... at socket 0
started device at port 0
nb_tx_queues is 2
nb_rx_queues is 2
eth:    link up - speed 0 Mbps, half-duplex
CPU 00| 11:25:20 <4>: Ethdev on port 0 initialised.
CPU 00| 11:25:20 <4>: Adding FDIR rules:
CPU 00| 11:25:20 <2>: This device does not support Flow Director (Error -95).
CPU 00| 11:25:20 <2>: Adding FDIR rules failed. (Error -95)
CPU 00| 11:25:20 <4>: init: module ethdev     SUCCESS
mempool_datastore: nvme_ctx        elem_len:104 nr_elems:1048576
mempool_datastore: nvme_swq        elem_len:16448 nr_elems:32768
DEVICE PARAMS: read cost 100, write cost 700
CPU 00| 11:25:21 <4>: init: module nvmemem    SUCCESS
Each SSD will be processed by 2 cores.CPU 00| 11:25:21 <4>: init: module nvmedev    SUCCESS
CPU 00| 11:25:21 <4>: init: percpu phase 0
CPU 00| 11:25:21 <4>: init: module timer      on 0: SUCCESS
CPU 00| 11:25:21 <4>: init: module mbuf       on 0: SUCCESS
CPU 00| 11:25:21 <4>: init: module memp       on 0: SUCCESS
CPU 00| 11:25:21 <4>: init: module tcpapi     on 0: SUCCESS
The size of RTE_ETH_TX_BUFFER_SIZE (eth_rx_max_batch) is 536
.tx_buffer: size-64, len-0.
CPU 00| 11:25:21 <4>: init: module ethdev     on 0: SUCCESS
CPU 00| 11:25:21 <4>: init: module nvmemem    on 0: SUCCESS
CPU 00| 11:25:21 <4>: init: module migration  on 0: SUCCESS
**ix: drivers/nvmedev.c:352: init_nvmeqp_cpu: Assertion `percpu_get(qpair)' failed.**
Aborted (core dumped)

### ubuntu 18 error message
**ubuntu@ip-172-31-7-111:~/elune/reflex4arm$ make -sj64 -C deps/dpdk install T=x86_64-native-linux-gcc DESTDIR=deps/dpdk/x86_64-native-linux-gcc**

...

**/home/ubuntu/elune/reflex4arm/deps/dpdk/mk/rte.sdkroot.mk:98: recipe for target 'all' failed make[2]: *** [all] Error 2 /home/ubuntu/elune/reflex4arm/deps/dpdk/mk/rte.sdkinstall.mk:60: recipe for target 'pre_install' failed make[1]: *** [pre_install] Error 2 
/home/ubuntu/elune/reflex4arm/deps/dpdk/mk/rte.sdkroot.mk:77: recipe for target 'install' failed make: *** [install] Error 2**

**Comment by mhxie** [comment]
@adamqqqplay Thanks for your attention to our latest progress on deploying reflex4arm on EC2 instances. The image I used to run ReFlex4ARM is [Amazon Linux 2](https://aws.amazon.com/amazon-linux-2/) and any i3 machine should work with it. I chose this because it supported better automatic networking configurations for inter-VPC accesses. And you need to attach at least two elastic network interfaces (ENI) to the machine because one of them will be using the DPDK ENA driver.

The most recent commit should have granted ReFlex4arm the ability to run as a systemd service and start automatically at boot time. In the script folder, the `configure.sh` will configure with the sample models, and the `run_reflex_server.sh` will configure the IP, the ENA driver, SPDK, and hugepages for you.

We are still actively working on this branch so the README is not up-to-date and redundant to ec2 deployment.

**Comment by mhxie** [comment]
The latest pull request #2 should have fixed the build issue on the Ubuntu image. Please run Ubuntu 20.04 LTS on AWS EC2 instances to verify.

**Comment by adam3q** [comment]
Thanks a lot! I will test it soon.

**Comment by mhxie** [comment]
For possible connection issues, please refer to this AWS [document](https://aws.amazon.com/premiumsupport/knowledge-center/ec2-ubuntu-secondary-network-interface/).

**Comment by adam3q** [comment]
Dear @mhxie ,
    When I deployed reflex4arm on the ubuntu 20 system of the i3.large server again, a floating point exception was triggered.
    Server side works normally, but when the client executes the following command, an error occurs.  
    `~/reflex4arm$ sudo ./build/dp -s 172.31.9.19 -p 1234 -w rand -T 1 -i 100000 -r 100 -S 0 -R 4096 -P 0`
![image](https://user-images.githubusercontent.com/29459113/114509165-c96f2100-9c67-11eb-8671-33c920dd09a2.png)

    Can you help me solve this problem? Thanks!

**Comment by mhxie** [comment]
@adamqqqplay Could you show me how does your ix.conf look like? And feel free to open a new issue with more context.

**Comment by adam3q** [comment]
@mhxie Sure, and I upload more context in new issue #6. Please take a look at your free time. Thank you!
